### ISSUE TITLE
These returns prevent freeing of the pointers allocated at the start of this function 

### ISSUE THREAD

**Issue by Taylorr82** [AlbertaSat/ex2_services#42]
Lots of malloc calls are made at the beginning of this function but they are only freed at the end of the functon, right before it returns SATR_OK. They should be freed before any of the returns in this function to prevent memory leaks

https://github.com/AlbertaSat/ex2_services/blob/0c66e3bc76a739c69d6c07171c8b6b113d1b6dc3/Services/source/communication/communication_service.c#L628
https://github.com/AlbertaSat/ex2_services/blob/0c66e3bc76a739c69d6c07171c8b6b113d1b6dc3/Services/source/communication/communication_service.c#L755

**Comment by ArashYzd** [comment]
Ah, yeah, I never actually encountered returning SATR_ERROR or SATR_PKT_ILLEGAL_SUBSERVICE because the ground station software enforced having a proper size and a valid subservice. Thanks for pointing it out. I think it'd be best if we assign the return value to a return variable instead of all the `return x` statements, then insert a break, and do the returning at the end of the [scope](https://github.com/AlbertaSat/ex2_services/blob/0c66e3bc76a739c69d6c07171c8b6b113d1b6dc3/Services/source/communication/communication_service.c#L764).

**Comment by ArashYzd** [comment]
The main issue is [resolved](https://github.com/AlbertaSat/ex2_services/pull/43). The ticket will remain open so that we remember to get back to the improvements discussed in the PR.
